# Nome do seu Workflow do GitHub
name: Generate Snake

# Controles de quando a action será executada
on:
  # Executa automaticamente a cada 6 horas
  schedule:
    - cron: "0 */6 * * *"

  # Permite que você execute a action manualmente na aba "Actions" do repositório
  workflow_dispatch:

# Define as tarefas que serão executadas
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Action que gera o jogo da cobrinha
      - name: generate snake.svg
        uses: Platane/snk@v3
        with:
          # O SEU NOME DE USUÁRIO DO GITHUB
          github_user_name: ${{ github.repository_owner }}

          # Lista de saídas
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Action para publicar os arquivos gerados no seu repositório
      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
